### ISSUE TITLE
Outdated implementation

### ISSUE THREAD

**Issue by fabrii** [digitalcredentials/bitstring#2]
Hi! The digitalcredentials bitstring implementation is outdated in comparison with https://github.com/digitalbazaar/bitstring.

The bitstring.get(pos) values do not match.

For example, the following representation in digitalbazzar 0, 0, 0, 0, 1, 1, 1, 1 is backwards represented in digitalcredentials: 1, 1, 1, 1, 0, 0, 0, 0. 

In digitalbazaar, leftToRightIndexing is the default value.

**Comment by kayaelle** [comment]
Thanks @fabrii - we'll look into this.

**Comment by kayaelle** [comment]
@dmitrizagidulin - please look into and update. Thanks!

**Comment by dmitrizagidulin** [comment]
@fabrii - This is now fixed, and a new package npm version is published at `@digitalcredentials/bitstring@3.1.2`.
Thanks!
